export default {
  'index': { display: 'hidden' },
  'linkace-overview': 'LinkAce Overview',
  'linkace-translations': 'LinkAce Translations',
  'linkace-v2-changelog': 'LinkAce v2 Changelog',
  'third-party-tools-libraries': 'Third-Party Tools & Libraries',
  'troubleshooting': 'Troubleshooting',
  'setup-with-docker': 'Setup with Docker',
  'setup-with-helm-kubernetes': 'Setup with Helm (Kubernetes)',
  'one-click-deploy-to-cloud': 'One-Click-Deploy to Cloud',
  'setup-without-docker': 'Setup without Docker',
  'post-setup-steps': 'Post-Setup Steps',
  'adjusting-the-database-collation': 'Adjusting the Database Collation',
  'linkace-upgrade-guide': 'LinkAce Upgrade Guide',
  'upgrade-from-linkace-v1': 'Upgrade from LinkAce v1',
  'the-dashboard': 'The Dashboard',
  'links': 'Links',
  'link-checks': 'Link Checks',
  'lists': 'Lists',
  'tags': 'Tags',
  'advanced-search': 'Advanced Search',
  'bookmarklet': 'Bookmarklet',
  'rss-feeds': 'RSS Feeds',
  'trash': 'Trash',
  'import-links': 'Import Links',
  'export-links': 'Export Links',
  'user-settings': 'User Settings',
  'user-api-tokens': 'User API Tokens',
  'system-settings': 'System Settings',
  'system-api-tokens': 'System API Tokens',
  'user-management': 'User Management',
  'sso-single-sign-on-with-oauth-or-oidc': 'SSO (Single-Sign-On) with OAuth or OIDC',
  'application-backups': 'Application Backups',
  'advanced-settings': 'Advanced Settings',
  'cli-commands-for-linkace': 'CLI Commands for LinkAce',
  'api-reference': {
    title: 'API Reference',
    type: 'page',
    href: '/api-docs/linkace-openapi'
  }
}
